### ISSUE TITLE
implement querybuilder support for child translation strategy

### ISSUE THREAD

**Issue by dbu** [doctrine/phpcr-odm#402]
similar to #353 but for child translation. with the recently merged join support, this should be possible with a ISCHILDNODE criteria. 

then update the doc that was added here: https://github.com/doctrine/phpcr-odm-documentation/pull/43

**Comment by dantleech** [comment]
Documentation still says this is not possible..

**Comment by dantleech** [comment]
Here.. http://doctrine-phpcr-odm.readthedocs.org/en/latest/reference/query-builder.html

**Comment by dbu** [comment]
ups, you are right. i just pushed a small update in https://github.com/doctrine/phpcr-odm-documentation/commit/4f2eb879eabeeb4e50094d0b479d9359a1dc350f
