### ISSUE TITLE
Get full tree

### ISSUE THREAD

**Issue by lowki** [doctrine/phpcr-odm#465]
Excuse my dumb question, but, is there any helper or an easy way to get the full tree from database?

**Comment by afoeder** [comment]
@lowki : can you elaborate on what you did by
> I've managed to do what I want using the phpcr session's getNodes() method.
please?

The document manager's getChildren method does only return the immediate children, right, and not the recursive ones?

…and sorry for digging this up.

**Comment by dbu** [comment]
yes, you only get the immediate children. you will need to recursively walk the tree if you need all of it. 

please open a new issue if you need further help, or talk to us in the symfony slack in the #phpcr channel. questions on very old issues can get lost - referencing the old issue is however a great help, of course!
