### ISSUE TITLE
Accessing children of a version of a document throws PHPCRException

### ISSUE THREAD

**Issue by mellowplace** [doctrine/phpcr-odm#573]
I have a class that has a property annotated like so...

     /**
     * @PHPCR\Children()
     */
    protected $accommodationTypes;

The class itself is marked versionable="full" but the children are not, they are simply versioned with the parent using "on parent version" copy.  The versioning does seem to work - I can see that the child nodes are copied to the frozen node when the parent is checked in.

When I call findVersionByName to get a specific parent document version and then try to access the first child node with Collection::first() I get the following exception...

"Doctrine\ODM\PHPCR\PHPCRException: Document is not managed and has no id"

Retrieving the editable document using find allows me to read the children just fine.  

I'm using PHPCR-ODM Version 1.1 and backing onto Apache Jackrabbit.

**Comment by mellowplace** [comment]
@dbu I have added another state as per your suggestion.

*One interesting point to note*

There is no issue with conflicting documents, a regular editable document such as...

/my/document

Does not have the same ID as it's versions, which are all stored under somewhere like

/jcr:system/...

So the work here may not be as extensive as originally thought - take a look at the pull request anyway and let me know your thoughts.

**Comment by dbu** [comment]
hm. PHPCR defines specific apis how to access versions. that they are nodes in /jcr:system is an implementation detail of jackrabbit.

will look at your pull request now!
