### ISSUE TITLE
Can't create database because PHPCR getDefaultSession tries to login

### ISSUE THREAD

**Issue by webberig** [doctrine/phpcr-odm#586]
My PHPCR implementation has worked in the past, but I recently started getting errors when setting up a new installation. If the database hasn't been initialized, I can't seem to perform any console command.

I created a service that uses @doctrine_phpcr.odm.default_document_manager. According to the stackrace, this service calls getDoctrinePhpcr_DefaultSessionService which tries a login.

You can see the complete stack trace in my Travis tests:
https://travis-ci.org/concerto-cms/CoreBundle/jobs/45771194

I think this started happening after upgrading to 1.2 of the Symfony CMF components. Why does it try to login to the DB before anything happens ? How can I avoid this problem ?

**Comment by webberig** [comment]
Small addition. It only happens if I define commands that use the default_document_manager. If I remove my commands it works. Other services that use the ODM don't seem to affect the console commands.

**Comment by webberig** [comment]
I've done a little digging and found the exact cause:

Apparently, all commands are being constructed when you use the Symfony console. 
I don't like to use ContainerAware classes, I define commands as services in which I put the necessary dependencies in the constructor.

Instead of making my commands ContainerAware, I created the commands as services and put document_manager in the constructor of the command.

When I call ie. doctrine:database:create, my command is being constructed as well. Because it depends on document_manager, this service is being constructed as well. And apparently, the document manager tries to call getDefaultSession which in its turn performs some query in the table phpcr_workspaces.

Would it be possible to avoid running queries during construction ?

**Comment by dbu** [comment]
this issue actually belongs to the DoctrinePhpcrBundle. i think the simple answer is to disable check_login_on_server: http://symfony.com/doc/current/cmf/bundles/phpcr_odm/configuration.html#jackalope-check-login-on-server

but it would be great if we manage to fix things properly. the command to create the database should not need the document manager.

commands as service only work with sf 2.4+ unfortunately, otherwise i would prefer that too.

**Comment by webberig** [comment]
Sorry for putting this issue in the wrong repo again! 

The documentation says it's disabled by default. Hoewever, when I look at the code:

        if (!isset($backendParameters['jackalope.check_login_on_server'])) {
            $backendParameters['jackalope.check_login_on_server'] = $container->getParameter('kernel.debug');
        }

it looks like it depends on the debug parameter if you don't set the option explicitly.

Ideally, Symfony shouldn't construct all commands when it only needs to execute 1 of them, imho...
For now, I will change my commands back to ContainerAware so the document_manager is only constructed when the command is being executed.

**Comment by webberig** [comment]
Or.. I could just disable the option explicitly... silly me!

**Comment by dbu** [comment]
right. where is the documentation that is incorrect? we changed it to this at some point but seem to have missed the doc.

we could of course just not check - the problem then is that you see configuration issues later than you would hope to see them. if you have an idea what we should do, i am happy to discuss - its very bad if we make bootstrapping phpcr a pain.

**Comment by webberig** [comment]
http://symfony.com/doc/current/cmf/bundles/phpcr_odm/configuration.html#jackalope-check-login-on-server

It says default: false
But it actually uses kernel.debug.

I don't really like options to depend on kernel.debug, but there may be a good reason why it was put there in the first place... I suppose documenting this behavior would be good.

I think the main problem here is the fact that Symfony constructs all commands, which is out of scope of Doctrine or PHPCR...

**Comment by dbu** [comment]
afaik @dantleech adressed this in jackalope-doctrine-dbal now. right?

**Comment by dantleech** [comment]
Yeah, I think this addresses it. At least there are no exceptions on new installs (with no database) now as the connection is lazily created.

**Comment by dbu** [comment]
thanks dan.

note that jackalope-doctrine-dbal 1.2 is not released yet, so you will only see this when installing the dev version of jackalope or once we released, which should happen soon i hope.
