### ISSUE TITLE
Make default PHPCR namespace configurable

### ISSUE THREAD

**Issue by dantleech** [doctrine/phpcr-odm#591]
It would be nice if we could change the default `phpcr` and `phpcr_locale` namespace aliases.

For example, to match up with an existing schema, or to just use shorter prefixes (and save some disk space).

In the DoctrineBundle there could be configuration:

``` yaml
system_namespace:
    locale: phpcr_locale
    odm: phpcr
```

This could be done with some central configuration object where you would be able to map arbitrary aliases to namespaces.

``` php
$nsFoo->getPrefix('locale');
$nsFoo->getPrefix('odm');
```

**update**: It is now possible to configure the translation namespace as noted below. This issue now relates to making the `phpcr` prefix configurable.

**Comment by lsmith77** [comment]
like I said, I am not sure if this is really sensible to allow this to be configured. just seems to risk causing all sorts of incompatibilities. that being said, both the document class mapper and the translation strategies are pluggable already for someone that really really wants to change this. though I do not know if all of that is configurable yet in DoctrinePHPCRBundle

**Comment by dantleech** [comment]
This may be naive, but isn't namespace mapping intended to avoid incompatibilities between different domains?

e.g. if I do this:

````
PHPCRSH> namespace:registry odm http://www.doctrine-project.org/projects/phpcr_odm
````

Then I should be able to import a repository which mapped that namespace to `phpcr`.

**Comment by lsmith77** [comment]
the chances of people using this to resolve conflicts between code versus the chances of them creating conflicts seem to be much lower. ie. you originally came with this feature request, because sulu was using its own namespace for the class to document mapping and you want to be able to switch to PHPCR ODM without migrating the data. this in effect would have created a situation where sulu (or at least some of its installs) are incompatible data-wise with other applications. which in turn means that queries written for sulu would not work with other systems etc.

**Comment by dbu** [comment]
this indeed is the intention of xml namespaces. in phpcr, there is the namespace remapping, which basically says that the backend prefix is up to the implementation, but you can use a different prefix in your code. this feature is however not implemented in jackalope at all.

i agree that ideally, namespace remapping would work everywhere but there is probably quite some effort involved both on jackalope and phpcr-odm level. i would prefer to invest our focus on more urgent things.

**Comment by dantleech** [comment]
@lsmith77 but I think it should work even from the code as you are using your namespace alias instead of the FQN.

But yeah, I realise that this probably doesn't work wth Jackalope etc right now. But in principle it should be possible I think, so it if I am correct it is a valid feature. (if I would have time to work on it is another matter).

**Comment by dbu** [comment]
@dantleech is this already possible for translations? https://github.com/doctrine/DoctrinePHPCRBundle/pull/185 - can we update the description to be more specific what should be made configurable?

**Comment by dantleech** [comment]
It would now be about making the `phpcr` prefix configurable, updated the description.

**Comment by dbu** [comment]
this never came up as a problem in the last 3 years, so im closing this. i guess it means in 1 week, somebody will need it :-)
