### ISSUE TITLE
Logger error in Doctrine\DBAL\Statement?

### ISSUE THREAD

**Issue by webbird** [doctrine/phpcr-odm#593]
I wondered why the 'params' are always empty in $logger->queries and found this:

    public function execute($params = null)
    {
        $logger = $this->conn->getConfiguration()->getSQLLogger();
        if ($logger) {
            $logger->startQuery($this->sql, $this->params, $this->types);
        }

So if $params are given and $this->params are logged, the passed $params are ignored. Shouldn't there be a line like

    if($params) && is_array($params) && count($params)) { $this->params = $params; }

?

**Comment by webbird** [comment]
Note: Solved this for me by using

    $logger->startQuery($this->sql, ((isset($params) && is_array($params) && count($params)) ? $params : $this->params), $this->types);

**Comment by lsmith77** [comment]
can you send a PR?

**Comment by webbird** [comment]
I would, but is the the solution of choice?

**Comment by dbu** [comment]
looking at https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Statement.php#L155-L162 this seems to have been fixed at some point. and issues on this should be tracked in the doctrine jira, not on the doctrine phpcr-odm project.
