### ISSUE TITLE
getDocumentId in DocumentManager?

### ISSUE THREAD

**Issue by dantleech** [doctrine/phpcr-odm#597]
It is often required that you need to get a document path without knowing about any accessors the document may have (if any) for that purpose.

Typically this happens when you are implementing event handlers.

Currently it is necessary to call `$documentManager->getUnitOfWork()->getDocumentId()`. The document manager already has calls which I think are on the same level, such as `DocumentManager#getDocumentChildren()`, `DocumentManager#getReferrers`, etc.

So I propose making this method part of the document manager somehow, maybe there should be two methods, e.g. `getDocumentUuid`, `getDocumnetPath`.

**Comment by dbu** [comment]
seems like a good idea to me. does orm offer something similar? if not, is there a reason why not? @Ocramius may i ask you for input on this?

if we do it, i would call the method getDocumentId and document that this is the path. not sure if we need a method for the uuid, this can be done through the metadata as well and for doing references, you can just pass the whole object. if we do it, i would call it getDocumentUuid, to stay with the mapping names we have.

**Comment by Ocramius** [comment]
The metadata API usually provides this

**Comment by dantleech** [comment]
@Ocramius the ID is not always mapped, so not available from the class metadata:

https://github.com/doctrine/phpcr-odm/blob/master/lib/Doctrine/ODM/PHPCR/Mapping/ClassMetadata.php#L1500

**Comment by lsmith77** [comment]
I guess it would make more sense to call it ``getId()``

**Comment by dbu** [comment]
i was going to argue for having "document" in the method name, but actually most methods on the DocumentManager do not have "Document" in them. so +1 for getId and getUuid.

**Comment by dbu** [comment]
note that getUuid has to throw an exception of the document is not referenceable.

**Comment by dantleech** [comment]
So are we basically saying that we should provide an API to the mapped fields in the ODM? e.g. `getReferrers`, `getDepth`, `getChildren`, `getNodeName`, `get...`. Maybe we should think about putting all of that in a DocumentHelper or something in 2.0.

**Comment by dbu** [comment]
we could even add that in 1.x and deprecate those methods we already have. something like $dm->getDocumentAccessor($document) ?

**Comment by dantleech** [comment]
Thats a good name. Makes me think it would be nice to split the document manager up completely so it is just a proxy for more more dedicated services.Then you could inject only what you need into your own classes.

e.g. `$documentManager = new DocumentManager($persister, $loader, $accessor)`.

**Comment by dantleech** [comment]
But yeah, I think adding this in 1.x would be interesting.

**Comment by ElectricMaxxx** [comment]
UoW resolves `getId()`by class metadata and the configured identifier property, right?

Should be easy to implement, or? Needed for RC-1 of version 2.0?
