### ISSUE TITLE
LocaleChooser includes implementation specific methods

### ISSUE THREAD

**Issue by dantleech** [doctrine/phpcr-odm#604]
The locale chooser interface includes the following methods which seem to be specific to the `LocaleChooser` implementation:

````php
    public function setLocalePreference($localePreference)

    public function setFallbackLocales($locale, array $order, $replace = false)

    public function setLocale($locale)

    public function getDefaultLocalesOrder()

    public function getDefaultLocale()
````

I *think* locale chooser need only implement:

````php
    /**
     * {@inheritDoc}
     */
    public function getFallbackLocales($document, ClassMetadata $metadata, $forLocale = null)
    {
    }

    /**
     * {@inheritDoc}
     */
    public function getLocale()
    {
    }
}

**Comment by dbu** [comment]
well setLocale is for setting the request locale. the rest indeed seems not to belong into the interface.

**Comment by dantleech** [comment]
But setLocale is also implementation specific as far as I can tell .. its called from the bundle. How the request locale is determined is implementation specific I think.

**Comment by dbu** [comment]
hm. but then how would the bundle know how tell the locale chooser what the preferred locale is?

**Comment by dantleech** [comment]
I think the listener should be coupled to the strategy, but then I can perhaps see the utility in having that method.

From my POV it is not required by the chooser I am implementing as it determines the locale through a service.

**Comment by dantleech** [comment]
Also is it necessary to pass the classmetadata to `getFallbackLocales` ? That could be obtained through a service passed to the constructor.

**Comment by dbu** [comment]
i think that was a mini-optimization to avoid having to look it up again. guess we could discard that. but changing the interface is a 2.0 thing.

**Comment by dbu** [comment]
having the setLocale is also relevant for #623 - depending on the solution we chose.

**Comment by dbu** [comment]
do we want to keep this open?

**Comment by dantleech** [comment]
I will close it now, if we encounter the issue again we can reopen.
