### ISSUE TITLE
Determine if document was loaded from a fallback locale

### ISSUE THREAD

**Issue by dantleech** [doctrine/phpcr-odm#608]
Currently it is not (I think) possible to determine if a document is loaded from a fallback.

We need to know if a document has been loaded from a fallback in order to show the user if a translation really exists for the document, or if it has been loaded from a fallback.

````php
$document = $dm->loadTranslation(null, '/path/to', 'fr', true); // load with fallback
$document->getLocale(); // en
````

So the `@Locale` mapping is the fallback locale, not the originally requested locale.

Would/is it possible to preserve the requested locale?

e.g.

````php
/**
 * Mapped to the fallback locale, if any (current behavior)
 * @Locale('fallback')
 */
protected $realLocale;

/**
 * Map the locale that was requested
 * @Locale('requested')
 */
protected $locale;
````

I don't really like the above options.. any suggestions? Currently I am hacking this into a LocaleChooser, which is pretty wrong.

**Comment by dbu** [comment]
i think you are correct. the reasoning is that if you save the document back, we don't want to accidentally create a "translation". i would assume that normally, the userland code knows what locale it requested, so it should be easy to detect when a fallback happened. 

if this is not convenient, what about using the post translation load event? if that event does not carry the requested locale, we should make it do so.

i am reluctant about adding yet another mapping, as i have the impression it is rarely needed. if i am mistaken we could add an attribute to Locale or have a RequestedLocale mapping

**Comment by dantleech** [comment]
yeah, the mapping would be awkward I think. Adding the information to the event is a good way forward, although it means adding a setter to the document, which is not ideal.

**Comment by dbu** [comment]
@dantleech where you able to solve this issue with the event listener, or do we need to add information to the event when a translation is loaded?

**Comment by dantleech** [comment]
I think I did solve it, so fine to close this one.

On 4 July 2015 12:51:19 CEST, David Buchmann <notifications@github.com> wrote:
>@dantleech where you able to solve this issue with the event listener,
>or do we need to add information to the event when a translation is
>loaded?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/doctrine/phpcr-odm/issues/608#issuecomment-118499943

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
