### ISSUE TITLE
Per-property namespaces?

### ISSUE THREAD

**Issue by dantleech** [doctrine/phpcr-odm#617]
It would be nice to be able to explicitly specify the namespace alias to use on a property-by-property basis.

e.g.

````
<field name="someContent" property="foo" namespace-alias="content" translated="true"/>
<field name="somethingCached" property="cache" namespace-alias="cache" />
<field name="somethingElseCached" property="cache" namespace-alias="cache" />
<field name="somethingElseCached" property="cache" namespace-alias="lcache"  translated="true"/>
````

To generate something like:

````
content:en-foo
cache:somethingCached
lcache:en-somethingElseCached
````

**Comment by dbu** [comment]
for non-translated properties, you can specify the namespace in the `property` if i am not mistaken. for child translation strategy this might just work as well. only for attribute translation, we have to be careful as those fields usually get their own namespace. but i see no reason why one should not be allowed to customize this. only the naming pattern of language_fieldname can not be changed other than with a custom translation strategy.

**Comment by dantleech** [comment]
You can specify them in the property names, but you cannot have two ":" in a property name, so you cannot do this with translated properties.

Do you know why we use a namespace for translation? Seems to me that the property name and the knowledge that it is translated should be enough.

**Comment by dbu** [comment]
the reason for namespace is that we can then use a mixin to allow such properties in case people use node types that do not allow any children. also, to avoid nameclashes that might happen otherwise because people are not aware that "content" makes a property "en-content".

**Comment by dbu** [comment]
@dantleech if somebody really needs non-namespace translations, he could write his own translation strategy to a variant of the attribute strategy.

do you think we need to do anything here, or is it ok as it is?

**Comment by dantleech** [comment]
Probably not within the scope of the current system. Fine for me to close.

On 4 July 2015 12:39:10 CEST, David Buchmann <notifications@github.com> wrote:
>@dantleech if somebody really needs non-namespace translations, he
>could write his own translation strategy to a variant of the attribute
>strategy.
>
>do you think we need to do anything here, or is it ok as it is?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/doctrine/phpcr-odm/issues/617#issuecomment-118499405

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
