### ISSUE TITLE
How to make nested where clauses with phpcr odm

### ISSUE THREAD

**Issue by lowki** [doctrine/phpcr-odm#619]
The [phpcr odm documentation](http://doctrine-phpcr-odm.readthedocs.org/en/latest/reference/query-builder-reference.html) seems to be quite clear on that point, but I can't manage to make it.
Here the raw mysql equivalent expected:

    SELECT (foo, bar, baz) FROM table
    WHERE (foo = 'foo') AND bar = 'bar' OR (baz = 'baz' OR baz = 'bazinga')

I tried something like this.

    $qb->from()
    ->document('Detours\MainBundle\Document\Product', 'p');

    $qb->where()
    ->andX()
    ->eq()
    ->field('p.foo')
    ->literal('foo');

    $qb->andWhere()
        ->eq()
        ->field('p.bar')
        ->literal('bar')
        ->end();

    
    $qb->where()
       ->eq()
       ->field('p.baz')
       ->literal('baz');
    $qb->orWhere()
      ->eq()
      ->field('p.baz')
      ->literal('baz');

**Comment by dantleech** [comment]
Something like the following I think:

````php
$qb->where()
    ->andX()
        ->eq()->field('p.foo')->literal('foo')->end()
        ->orX()
            ->eq()->field('p.bar')->literal('bar')->end()
            ->orX()
                ->eq()->field('p.baz')->literal('baz')->end()
                ->eq()->field('p.baz')->literal('bazinga');
````

**Comment by dbu** [comment]
As i wrote on http://stackoverflow.com/questions/29233792/how-to-make-nested-where-clauses-with-phpcr-odm/29251261


Are you aware that you have a "where" in the middle, after andWhere for p.bar = bar? that will eliminate the previous where clause afaik. Try something like 
```
$qb->where()
  ->orX()
    ->andX()
      ->eq()->...->end()
      ->eq()->...->end()
    ->end()
    ->orX()...
```

**Comment by dbu** [comment]
to debug, you can also print out the phpcr query that is generated.

**Comment by lowki** [comment]
Once again, you save me.
Thank you very much both of you.
