### ISSUE TITLE
Dependency issue with doctrine/orm

### ISSUE THREAD

**Issue by kminh** [doctrine/phpcr-odm#624]
Hi,

Doctrine ORM 2.5.0 has just been released, and now it explicitly requires `doctrine/common >= 2.5.x` while `doctrine/phpcr-odm` is explicitly requiring `doctrine/common ~2.4.0`. Is there a recommended way to resolve this conflict? Before I can use aliases but now it seems impossible.

I would avoid reverting to Doctrine ORM 2.4.0 at all cost because my current app depends on some of 2.5's features.

Thanks.

**Comment by dbu** [comment]
This look like  a mistake on our sie. We should depend on ~2.4 , not 2.4.0
so any 2.x is OK. Can you submit a pull request to change this, against the
1.1 branch? Will then tag a fixed release tomirrow

**Comment by kminh** [comment]
Can't seem to build on 1.1 branch hmm

**Comment by dbu** [comment]
fixed by #626
