### ISSUE TITLE
SimpleVersionable level not supported by Jackrabbit Server?

### ISSUE THREAD

**Issue by eiannone** [doctrine/phpcr-odm#631]
As described here: https://groups.google.com/forum/#!topic/jackalope-dev/uxfuFwWG85Q, the simpleVersionable level does not seems to work with Apache Jackrabbit server (tested with version 2.8.0 and 2.10.0).
Trying to checkin or chechout nodes mapped to documents with this versioning mode results in an UnsupportedRepositoryOperationException.
Jackrabbit server seems to refuse doing checkin on nodes with mixin mix:simpleVersionable.
Changing versionable attribute from "simple" to "full" on the same document class will enable versioning, adding the supported mixin "mix:versionable"

**Comment by dbu** [comment]
indeed, we have to consider jackalope-jackrabbit to not support mix:simpleVersionable

@eiannone may i ask you to update the phpcr-odm-documentation to add a warning in https://github.com/doctrine/phpcr-odm-documentation/blob/master/en/reference/versioning.rst saying that jackalope-doctrine-dbal does not support versions at all, and jackalope-jackrabbit only supports full? and also at http://docs.doctrine-project.org/projects/doctrine-phpcr-odm/en/latest/reference/annotations-mapping.html#annref-document to say that not every phpcr implementation supports versions?

**Comment by eiannone** [comment]
Done: https://github.com/doctrine/phpcr-odm-documentation/pull/72

**Comment by dbu** [comment]
see https://github.com/doctrine/phpcr-odm-documentation/pull/72
