### ISSUE TITLE
Weird alias [0_ for tables

### ISSUE THREAD

**Issue by dipens** [doctrine/phpcr-odm#635]
Hi I'm trying to implement https://github.com/Abhoryo/APYDataGridBundle with SQL Server . I am facing a simple but not solvable bug with doctrine. When I do a findAll on a table, doctrine gives me just fine results. However if I do it with the APY bundle doctrine adds a weird alias "[0_" which I can't seem to find where its coming from. Is there a possible fix for this?

**Comment by dantleech** [comment]
Hi. I think you wanted to create the [Doctrine2 issue tracker](http://www.doctrine-project.org/jira/browse/DDC). PHPCR-ODM != Doctrine ORM :)
