### ISSUE TITLE
Flushing one removed document throws an exception

### ISSUE THREAD

**Issue by coudenysj** [doctrine/phpcr-odm#637]
The following code

```php
$manager->remove($resource);
$manager->flush($resource);
```
throws an exception in the UnitOfWork class
```
Document has to be managed for single computation Symfony\Cmf\Bundle\MenuBundle\Doctrine\Phpcr\MenuNode@0000000075dd08b200000000252e59a6 (/be/menus/footer/press)
```

This is caused by the check in `Doctrine\ODM\PHPCR\UnitOfWork::computeSingleDocumentChangeSet()`

```php
public function computeSingleDocumentChangeSet($document)
{
    $state = $this->getDocumentState($document);
    if ($state !== self::STATE_MANAGED) {
        throw new InvalidArgumentException('Document has to be managed for single computation '.self::objToStr($document, $this->dm));
    }
    //...
}
```

Should this check be changed to keep STATE_REMOVED in mind?

I'm happy to provide a pull request, if this is the way to go. The current solution is to call flush without arguments.

**Comment by lsmith77** [comment]
can you check how its done in the ORM?

**Comment by coudenysj** [comment]
The `REMOVED` state is [checked too](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/UnitOfWork.php#L474).

I will create a pull request for this.

**Comment by lsmith77** [comment]
thanks!

**Comment by lsmith77** [comment]
please create the PR on top of the 1.2 branch so that we can do a bug fix release and then merge your changes into master.
