### ISSUE TITLE
AnnotationReader doesn't import annotations from used traits

### ISSUE THREAD

**Issue by crazycodr** [doctrine/phpcr-odm#639]
We hit a problem today where softdeleteable just wouldn't work and after a while we found out that the AnnotationReader simply doesn't import annotations from used traits, only the methods and properties are imported in regards to traits.

I'm not entirely sure this is a bug since the properties and methods are already parsed so i'd like a quick explanation why the class annotations are not merged into the imports.

**Comment by dbu** [comment]
did you build a softdeleteable extension for phpcr-odm or was this meant for https://github.com/doctrine/doctrine2?

afaik traits is treated in php as copy-paste and trait level annotations will be lost. using a trait is not the same as inheritance. but best check with whoever provided that trait to ask how he expects it to work.

**Comment by crazycodr** [comment]
No i'm using the one from gedmo/doctrine-extensions through stof/doctrine-extensions-bundle. Everything works as expected if i put the Gedmo\Mapping\Annotation\SoftDeleteable annotation on the entity, but if i put it on our own SoftDeleteableTrait so we can apply it to many entities at once, it stops working! I have to import the trait into the entity and also add the Gedmo\Mapping\Annotation\SoftDeleteable annotation.

**Comment by crazycodr** [comment]
I fixed the problem by simply adding:


        foreach($class->getTraits() as $trait)
        {
            $annotations = array_merge($annotations, $this->parser->parse($trait->getDocComment(), 'class ' . $trait->getName()));
        }

to

    public function getClassAnnotations(ReflectionClass $class)

after

    $annotations = $this->parser->parse($class->getDocComment(), 'class ' . $class->getName());

**Comment by crazycodr** [comment]
Should i post a PR, or will it be refused... That is the question :)

**Comment by dbu** [comment]
the annotation parser is in doctrine/annotations. their github project has issues deactivated as they prefer to use jira for issue tracking. i found no annotations in jira however, only http://www.doctrine-project.org/jira/browse/DCOM for commons. @Ocramius do you have input where this should be reported/discussed?

or if its just this small change, you could do a PR on annotations to ask what they think of that change.

**Comment by crazycodr** [comment]
I'll PR it and see what their input is, thanks @dbu
