### ISSUE TITLE
Mixins in xml mapping are not properly inherited

### ISSUE THREAD

**Issue by uwej711** [doctrine/phpcr-odm#640]
Example: class A defines mixin a, class B extends A and defines mixin b
Expected result: class B has mixins a and b, but you have to define mixin a again on class B to get the desired result.

Trying to add a failing test.

**Comment by dbu** [comment]
i think that was kind of on purpose to allow preventing to inherit a mixin.
though semantically it makes little sense to have a child class not have a
mixin of the parent. we should maybe have an option to not inherit or
remove specific mixins and inherit by default. there is a BC problem
however. maybe we can do it as minor versiin, with a warning in changelog.
Am 12.06.2015 09:02 schrieb "Uwe Jäger" <notifications@github.com>:

**Comment by dantleech** [comment]
What would PHPCR do in such a case? i.e.

````
[mytype] < nt:unstructured, somemixin

[myinheritedtype] < mytype
````

I think `myinheritedtype` would inherit the mixin.

**Comment by uwej711** [comment]
I think the issue is that we don't "merge" the mixins from class A and B and just look at the mixins. If I remember right, class B will inherit  mixin a as long as class B does not define another mixin. I need to  investigate that bit and check whether it is an issue with the XmlDriver or with ClassMetadata.

**Comment by dbu** [comment]
i think your analysis is correct uwe. and i think merging by default
would be right. its probably a problem with all mapping drivers.

**Comment by dbu** [comment]
@uwej711 do you have time to look into this anytime soon? would be good if we could include this in the upcoming 1.3 version of phpcr-odm.

**Comment by uwej711** [comment]
I had a look at this (and changed the implementation) but now I have a failing test:
```ClassMetadataFactoryTest::testLoadMetadataClassInheritanceChildCanOverride()``` which assumes that a child class can override the document definitions of the parent class.

So either we leave this as it is or change the failing tests (i.e. you can not override the parent class' mixins) or we add an option to the mixins definition to let the developer decide whether mixins should be merged or overridden.

**Comment by dbu** [comment]
hm, could we do the options `add-mixins` and `replace-mixins` and
deprecate the use of `mixins`? i guess the other options are implicit
replaces, e.g. the primary type? i think adding mixins is more expected
and natural, but that would be a BC break. then again it should rarely
be a problem if an extending class has additional mixins so maybe just
keep `mixins` and change it to adding, and provide an additional
`replace-mixins` for when replacing is wanted.

**Comment by uwej711** [comment]
I ran into this when I extended the document classes from the media bundle (adding another property to an image needs an extra mixin) and I had to readd the mixins from the bundle. This is not what you expect. Overriding mixins of a parent class may only make sense when you override the node type to. Anyway this will break BC. But keeping mixins with changed semantics and adding replace-mixins should be the least problematic.

**Comment by dbu** [comment]
yeah. lets call it a bugfix. and its a minor version, not a dot release
so should be ok. can you update your PR accordingly? and make sure to
explain in che CHANGELOG

**Comment by uwej711** [comment]
OK, will do this later

2015-07-08 9:01 GMT+02:00 David Buchmann <notifications@github.com>:

**Comment by uwej711** [comment]
Adding a replace-mixins will need some sanity checks to only allow either mixins or replace-mixins. I suggest having another array in ```ClassMetadata``` for the replace-mixins which allows me to do the check once in this class.

**Comment by dbu** [comment]
i guess having that as a separate thing in ClassMetadata makes sense, yes. do we need to sanity check that there is actually a base class with mixins to allow replace-mixins? i would say we don't need to check that.

the ClassMetadata would then just check if it has replace mixins and if so take those, otherwise merge its mixins with the parent::getMixins which follows the same logic. so we walk up inheritance up to the point where we encounter a replace-mixins or are at the top.
