### ISSUE TITLE
1.3 release

### ISSUE THREAD

**Issue by dantleech** [doctrine/phpcr-odm#645]
It would be good to make a new release in order that people can benefit from the new annotations, and and also for the changes I made to enable the query builder to be used by other systems.

We should review the changes and note anything suspect in this issue:

https://github.com/doctrine/phpcr-odm/compare/1.2.3...master

**Comment by lsmith77** [comment]
we should also look at open PRs .. at this point I only see https://github.com/doctrine/phpcr-odm/pull/622 as a candidate to be merged ..

**Comment by lsmith77** [comment]
I marked a few things for 1.3 and moved an open ticket from the 1.2 milestone:
https://github.com/doctrine/phpcr-odm/milestones/1.3

**Comment by lsmith77** [comment]
we should also decide on the ``@trigger_error`` stuff .. either uncomment it .. or remove it from the code

**Comment by lsmith77** [comment]
this should also be fixed before the release https://github.com/doctrine/phpcr-odm-documentation/issues/73

**Comment by dbu** [comment]
good for me, created #646 about the failing lowest version tests.

**Comment by dantleech** [comment]
Why do we require `symfony/console ` and `doctrine/data-fixtures` is non-dev dependencies?

**Comment by dantleech** [comment]
Have read the change set and can't see anything obviously wrong.

**Comment by dantleech** [comment]
Also, unsure to what extent we can fix the deprecation warnings from the Symfony debug component (?):

https://github.com/sulu-io/sulu-standard/pull/466#issuecomment-113486112

**Comment by dbu** [comment]
some of the commands have existed for a long while: https://github.com/doctrine/phpcr-odm/tree/master/lib/Doctrine/ODM/PHPCR/Tools/Console/Command

maybe we only now noticed that we have this dependency? but for commands we really should make that optional and move it to suggest + require-dev and document it. for data-fixtures as well, if we even need them - i thought the integration code lives in the data fixtures repository, not here.

**Comment by dantleech** [comment]
+1

On 6 July 2015 09:28:10 CEST, David Buchmann <notifications@github.com> wrote:
>some of the commands have existed for a long while:
>https://github.com/doctrine/phpcr-odm/tree/master/lib/Doctrine/ODM/PHPCR/Tools/Console/Command
>
>maybe we only now noticed that we have this dependency? but for
>commands we really should make that optional and move it to suggest +
>require-dev and document it. for data-fixtures as well, if we even need
>them - i thought the integration code lives in the data fixtures
>repository, not here.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/doctrine/phpcr-odm/issues/645#issuecomment-118755796

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lsmith77** [comment]
so from my POV we are ready to do 1.3.0-rc1

**Comment by lsmith77** [comment]
BTW IIRC RMT adds the version to the changelog .. so we should probably remove the explicit version in the changelog ..

**Comment by lsmith77** [comment]
https://github.com/doctrine/phpcr-odm/releases/tag/1.3.0-rc
