### ISSUE TITLE
"Notice: Undefined index" when using parent ID strategy and proxies

### ISSUE THREAD

**Issue by WouterJ** [doctrine/phpcr-odm#663]
For the first time ever, I've added the PHPCRODM bundle to a current Symfony project and start to make it work. I'm always getting a "Notice: Undefined index" because of [this line](https://github.com/doctrine/phpcr-odm/blob/master/lib/Doctrine/ODM/PHPCR/Proxy/ProxyFactory.php#L101):

```php
$this->createCloner($classMetadata, $classMetadata->reflFields[$classMetadata->identifier])
```

As my document uses the parent ID strategy, it has a `@ParentDocument` and `@Nodename`, but no `@Id`. This means `$classMetadata->identifier` is `null`, which of course makes PHP error as keys can't be null.

I have no idea to fix this and if this is a bug in  the code or a misconfiguration on my side. If it's the latter, there should be a better exception thrown in case `identifier` is null imo.

/cc @lsmith77 @dbu

Relevant code: https://gist.github.com/WouterJ/45684a10f1d93665090a

**Comment by lsmith77** [comment]
in the code you did not include your entity with the parent document mapping. can you add this .. either way this is clearly a bug .. either it needs an explicit exception or it should just work.

**Comment by WouterJ** [comment]
Included the correct document now: https://gist.github.com/WouterJ/45684a10f1d93665090a#file-milestone-php

**Comment by lsmith77** [comment]
i have a reproducible test case. looking into what kind of solution we can provide.

**Comment by lsmith77** [comment]
@WouterJ see https://github.com/doctrine/phpcr-odm/pull/664

**Comment by dbu** [comment]
@WouterJ #664 is merged and should fix this. thanks for reporting
