### ISSUE TITLE
Release of the stable version

### ISSUE THREAD

**Issue by pamil** [doctrine/phpcr-odm#673]
I've seen that there weren't any changes made since rc4. What's the planned date of releasing version 1.3? It would be great to have stable version available, since it is our last *rc* dependency in Sylius :)

**Comment by dbu** [comment]
i think we are ready to tag. there seems no open pull request that needs
to go in, and we are not aware of any regressions at this time. there
are some open bugs but they existed with the 1.2 version as well

@lsmith77 if you agree, i can tag tomorrow morning

**Comment by dbu** [comment]
okay, took a bit longer. but i just released 1.3.0!

**Comment by dantleech** [comment]
\o/
