### ISSUE TITLE
Filters support

### ISSUE THREAD

**Issue by pamil** [doctrine/phpcr-odm#674]
Hello! I'm currently developing a project that needs to support multitenancy. I tried solving it by using workspaces and logic that dynamically changes them. However, it isn't the cleanest solution and I'm looking for alternatives. 

I wonder if there is something that prevents PHPCR-ODM from implementing filters support like the one in [Doctrine ORM](http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/filters.html) or [Doctrine ODM (MongoDB)](http://doctrine-orm.readthedocs.org/projects/doctrine-mongodb-odm/en/latest/reference/filters.html). If there aren't any reasons not to implement them, I'd be more than happy to contribute :)

**Comment by dbu** [comment]
generally speaking, you should aim to use path (document id) lookups
over SQL2 queries when possible, as they are much more performant. have
documents reference other documents and those things...

that said, i don't see a reason why we should not have filters in
phpcr-odm, if somebody implements them. might be quite some work
however, but at least we do have a query language model and a parser for
sql2 so it should be feasable. i don't have time to work a lot on this,
but am happy to provide feedback and help you figure out where to add
what to make it happen @pamil.
