### ISSUE TITLE
PHP 7.0 incompatibility : Cannot use 'String' as class name as it is reserved

### ISSUE THREAD

**Issue by fabricek** [doctrine/phpcr-odm#678]
I ve updated to php7.0 and last version 1.3 of phpcr-odm. And still have this issue :

PHP Fatal error: 
- Cannot use 'String' as class name as it is reserved in .../vendor/doctrine/phpcr-odm/lib/Doctrine/ODM/PHPCR/Mapping/Annotations/String.php on line 32

Next and similar errors : 
- Cannot use 'Int' as class name as it is reserved in Doctrine/ODM/PHPCR/Mapping/Annotations/Int.php on line 34
- Cannot use 'Float' as class name as it is reserved in Doctrine/ODM/PHPCR/Mapping/Annotations/Float.php on line 34

I was thinking the problem were solved with 1.3, but it seems not. Need help cause i saw other topics without finding a workaround to solve it. Thanks.

**Comment by dbu** [comment]
according to travis, this *is* solved indeed: https://travis-ci.org/doctrine/phpcr-odm/jobs/95615403

could it be that you still use the deprecated annotations `@String` and `@Float`? i think we issue deprecation warnings on php 5 when you use them, check with the symfony deprecation helper.

you need to replace these annotations with `@Field(type="string")` and so on. we still have the String class for BC with older applications that run on PHP 5. but they only break when the loading is triggered.

**Comment by fabricek** [comment]
Thanks very much for your anwser. 
I ve checked for files containing `@Float` or `@Int` but i didn't find any. I don't think my symfony app use this syntax. (I've checked in all files with grep)
But if i carrefully read the error mentionned above it seems the errors are in the vendor Doctrine/ODM/PHPCR/ files. I don't understand.

**Comment by dbu** [comment]
@fabricek as soon as something triggers the load of those classes, you will see the error at the place the annotations are defined. the annotations might be `@PHPCR\Float` or `@PHPCRODM\Float` - did you look at your model classes? did you also check the vendors? can you see some stack trace? did you try to rm -r app/cache/* to be sure its not a caching problem?

**Comment by dbu** [comment]
@fabricek any luck with this one?

**Comment by WouterJ** [comment]
@fabricek make sure your bootstrap file (e.g. `app/autoload.php`) doesn't load the annotations. Something like this:
```php
AnnotationRegistry::registerFile(__DIR__.'/../vendor/doctrine/phpcr-odm/lib/Doctrine/ODM/PHPCR/Mapping/Annotations/DoctrineAnnotations.php');
```

This file is no longer needed, as annotations can be autoloaded using the normal Composer autoloader now. When this statement is added, the String class is always loaded, no mather if you use it or not.
