### ISSUE TITLE
findBy doesn't work with arrays of values

### ISSUE THREAD

**Issue by vudaltsov** [doctrine/phpcr-odm#680]
The example, given [here](http://docs.doctrine-project.org/projects/doctrine-phpcr-odm/en/latest/reference/working-with-objects.html#by-simple-conditions):

    ->findBy(array('age' => array(20, 30, 40)));

ends with an error `array to string conversion in PHPCR\Util\QOM\BaseSqlGenerator::evalLiteral`

actually, any attempt to use `eq()->field(...)->literal(array(...))` was unsuccessfull.

The question is, whether the documentation is incorect, or `::evalLiteral` should have `if(is_array())` part.

How can I use `WHERE field IN (...)` inside query builder?

**Comment by dantleech** [comment]
PHPCR itself does not support this: https://github.com/phpcr/phpcr/blob/master/src/PHPCR/Query/QOM/LiteralInterface.php#L18

Although I think it would be valid to support this in the query builder in some form. In the meantime
you can emulate this behavior.

I havn't tested this (would be suprised if it worked), but I think this would be the general approach:

```php
$constraint = $queryBuilder->where()->orX();
$values = array('1', '2', '3');
foreach ($values as $index => $value) {
    // literal should match any value in an array field.
    $constraint = $constraint->eq()->field('age')->literal($value)->end()

    // if this the the penultimate value, then the next constraint should be "eq" to complete the "orX" chain.
    if ($index === count($values) - 2) {
        continue;
    }

    // add orX constraint as the second operand to orX
    if ($index < count($values) - 1) {
        $constraint = $constraint->orX();
    }
}
```

/cc @lsmith77 @dbu

**Comment by vudaltsov** [comment]
@dantleech, thank you, I will try this today. Mostly I worry about documentation, cause it shows an invalid example, if I got it right.

Is there any problem with creating an `->in()` constraint? I guess, it's a frequently used feature.

**Comment by dantleech** [comment]
Which documentation? I don't see any reason not to create such a constraint at this moment

**Comment by dantleech** [comment]
Oh I am blind. Ignore that previous comment.

**Comment by dantleech** [comment]
Created doc PR to remove that reference: https://github.com/doctrine/phpcr-odm-documentation/pull/79

**Comment by ElectricMaxxx** [comment]
I would like to see it in querybuilder.

**Comment by dbu** [comment]
documentation is fixed, created an issue for the new feature idea => #681 
if anybody wants to work on it, please do.

**Comment by vudaltsov** [comment]
@dbu, @dantleech 

Thank you. I want to try to work on this (I've already done this in my project). I will create a PR after NY.
