### ISSUE TITLE
ReferenceManyCollection doesn't work with strategy 'path'

### ISSUE THREAD

**Issue by zamorem** [doctrine/phpcr-odm#687]
When using ReferenceManyCollection with "path" strategy reference nodes don't get loaded and error HTTP 403: Invalid UUID:  is reported.

It is because in ReferenceManyCollection::initialize() nodes are loaded  with SessionInterface::getNodesByIdentifier() which only accepts uuids not paths.

**Comment by dbu** [comment]
do you think you can provide a pull request to make ReferenceManyCollection::initialize() check the strategy and use the correct call when its paths?

**Comment by zamorem** [comment]
yes I can try that ... is it ok to check for strategy with:
$this->dm->getMetadataFactory()->getMetadataFor(get_class($this->document))->getAssociation($this->property)['strategy'] or is there some more straightforward way? I'm not that acquainted with phpcr code...

**Comment by dbu** [comment]
i would prefer to add a constructor argument to the
ReferenceManyCollection. it would have to come after the locale and
could be $referenceType = 'uuid' and in UnitOfWork you pass 'path' if
the metadata says its path. you have the metadata available to pass the
property name anyways. i found 3 places of `new ReferenceManyCollection`
that would need to be updated.

it would be great if you also can add a case to the
Doctrine\Tests\ODM\PHPCR\Functional\ReferenceTest using the
RefTestObjByPath . we seem to testCreateByPath but not loading a
document that uses reference by path, hence we did not see the bug.
(maybe start with the test to see it actually fails, then see its fixed
with your fixed)

**Comment by dbu** [comment]
fixed in #689
