### ISSUE TITLE
Could not find a mapped field or association named "jcr:uuid" for alias "content"

### ISSUE THREAD

**Issue by billsworld** [doctrine/phpcr-odm#692]
I am trying to use the ```queryBuilder``` to generate a query using jcr:uuid like this.

```
SELECT comments.* 
FROM [nt:unstructured] AS comments 
INNER JOIN [nt:unstructured] AS content ON content.[comments]=comments.[jcr:uuid]
```

The problem is that I am getting the error: ```Could not find a mapped field or association named "jcr:uuid" for alias "a"```

Here is the php code
```
$qb->fromDocument('AppBundle\Document\CommentDocument', 'comment')
    ->addJoinInner()
    ->right()->document('AppBundle\Document\ContentDocument', 'content')->end()
    ->condition()->equi('content.comments', 'content.uuid');
```

I have also tried to use ``->condition()->equi('content.comments', 'content.id');`` which doesn't throw the error but also does not return results.

How can I do a JOIN using jcr:uuid using the query builer?

For reference my Doctrine mapping looks like this for the id
```
    <mapped-superclass
        name="AppBundle\Document\AbstractDocument"
        >

        <mixins>
            <mixin type="mix:created" />
            <mixin type="mix:lastModified" />
        </mixins>

        <id name="id">
            <generator strategy="PARENT"/>
        </id>
...
```

**Comment by dbu** [comment]
does your CommentDocument map a field you call uuid? there is a mapping
for the jcr:uuid field - you need to map that in your document, then
this should be available in the query builder

**Comment by billsworld** [comment]
That's what I want to do but can't figure out how. Is this documented? Have an example?

**Comment by dbu** [comment]
there is supposed to be `@Field(type=uuid)`, does that not work?

**Comment by dantleech** [comment]
think we need to update the docs, as they still use the deprecated `@Uuid` but both should work: http://doctrine-orm.readthedocs.org/projects/doctrine-phpcr-odm/en/latest/reference/annotations-mapping.html#uuid²

**Comment by billsworld** [comment]
Sorry. How should that look with xml mapping. Shouldn't it be used here?
https://github.com/symfony-cmf/BlockBundle/tree/master/Resources/config/doctrine-phpcr

**Comment by billsworld** [comment]
It is interesting that the uuid is not used in any of the Symfony CMF code that I can find.

This seems to work for xml mapping
```
<field name="uuid" type="uuid" />
```

It is also intersting to note that this does not throw an error, there is not validation on the type
```
<field name="uuid" type="something_that_does_not_exist" />
```

**Comment by billsworld** [comment]
I take it back, the query needs to use "jcr:uuid", not just "uuid". I updated the original title

It seems there is still no way to do this...

```
->condition()->equi('c.comments', 'a.jcr:uuid');
```

**Comment by billsworld** [comment]
Here is a possible fix https://github.com/doctrine/phpcr-odm/pull/694
