### ISSUE TITLE
Could not find a mapped field or association named "*" for alias "content"

### ISSUE THREAD

**Issue by billsworld** [doctrine/phpcr-odm#693]
I am trying to use the ```queryBuilder``` like this.

```
SELECT comments.* 
FROM [nt:unstructured] AS comments 
```

The problem is that I can't get the ```comments.*``` part to work

Here is the PHP code:
```
$qb->select()
    ->field('comments.*');
```

Is it possible to use a wildcard like this using the queryBuilder?

**Comment by dbu** [comment]
afaik no, you need to specify one document class to select from. if you
want to find anything, regardless of document class, you need to use a
phpcr query. the document manager has a method that accepts a phpcr
query to find documents. you will get back a mixed list of documents of
the classes that are found in phpcr

**Comment by billsworld** [comment]
Using a.* would be specifying one document class. 

Using a raw query is not an option for this case. The query is being run inside sonata phpcr admin callback.

**Comment by dbu** [comment]
how about `$qb->from('FQN\Comment')`? you usually query for documents, not for specific fields (also, a.* in PHPCR is not all properties, but only the path and other basic things.)

in sonata, you can specify which field to display in a dropdown or field, e.g.

```
        $formMapper
            ->with('form.group_general')
                ->add(
                    'targetItem',
                    'phpcr_document',
                    array(
                        'choices' => $this->getItems(),
                        'class' => 'AppBundle\Document\Item',
                        'property' => 'id', // this can specify any field of the document that should be used for selecting
                    )
                )
        ;
```

**Comment by billsworld** [comment]
Ended up working this out by updating our schema to better use the hierarchy provided by PHPCR.
