### ISSUE TITLE
queryBuilder disable document type check

### ISSUE THREAD

**Issue by billsworld** [doctrine/phpcr-odm#695]
I am trying to generate a query like this in order to get the comments associated with content.

```
SELECT comments.* 
FROM [nt:unstructured] AS comments 
INNER JOIN [nt:unstructured] AS content 
ON content.[comments]=comments.[jcr:uuid] 
WHERE ISSAMENODE(content, '/posts/14567094700770562')
```

I am using code like this
```
$qb->from()->document('AppBundle\Document\CommentDocument', 'comments');

$qb->from('comments')->joinInner()
    ->left()->document('AppBundle\Document\CommentDocument', 'comments')->end()
    ->right()->document('AppBundle\Document\ContentDocument', 'content')->end()
    ->condition()->equi('content.comments', 'comments.uuid');

$qb->andWhere()->same('/posts/14567094700770562', 'conent');
```

The trouble is, this is generating a query like the one below

```
SELECT * 
FROM [nt:unstructured] AS comments
INNER JOIN [nt:unstructured] AS content
ON content.[comments]=comments.[jcr:uuid] 
WHERE ((ISSAMENODE(content, [/posts/14567094700770562]) 
AND (comments.[phpcr:class] = 'AppBundle\Document\CommentDocument' 
OR comments.[phpcr:classparents] = 'AppBundle\Document\CommentDocument')) 
AND (content.[phpcr:class] = 'AppBundle\Document\ContentDocument' 
OR content.[phpcr:classparents] = 'AppBundle\Document\ContentDocument'))
```

Is there a way to prevent the conditions after the ISSAMENODE part from showing up? I am using the query builder b/c this is part of a Sonata admin filter https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/blob/master/Filter/CallbackFilter.php;

**Comment by dantleech** [comment]
Is there a problem with the query results? The extra criteria are required as we map the class type to a property on the node.

**Comment by billsworld** [comment]
@dantleech yes, with the added conditions it is an empty result

**Comment by dantleech** [comment]
They are required as otherwise you would join ALL documents as we are joining the node type `nt:unstructured` to the node type `nt:unstructured` - instead of the RSBMS equivalent of joining the `content` table to the `comments` table. (we should really map node types to classes in a similar way, but thats a different discussion).

It is maybe worth having a look at the DBAL SQL to identify the issue, or perhaps try with the Jackrabbit backend and see if it works as expected there.

**Comment by lsmith77** [comment]
@billsworld I would recommend to follow the route that @dantleech suggested .. ie. look at the generated SQL statement using the profiler to figure out what might be wrong and then submit a ticket on  https://github.com/jackalope/jackalope-doctrine-dbal with details

**Comment by dbu** [comment]
PHPCR provides a hierarchical data repository. this query looks a lot like thinking in terms of relational databases. can the same comment instance occur in several documents? if not, i would make the comments children of the document. then your query could be:

```
$qb
  ->from()->document('AppBundle\Document\CommentDocument', 'comment')
  ->where()->child('/posts/14567094700770562', 'comment')
;
```

or if you have nested comments `where()->descendant('/posts/1234', 'comment')`. though if you have nested posts as well, you need to create a GenericDocument child "comments" in each post and then use `where()->descendant('/posts/1234/comments', 'comment')` to avoid ending up with comments from child posts.

**Comment by billsworld** [comment]
I think you might be right. This could be a better case for using the document children. Wouldn't the comments document under each post have to be a Container type and not just generic?

Will give it a go.

**Comment by dbu** [comment]
> Wouldn't the comments document under each post have
> to be a Container type and not just generic?

for the search, you can use anything. but in your object model, having a
CommentContainer or something could be more elegant indeed.

**Comment by billsworld** [comment]
Went ahead updated the data structure to use the hierarchy like this /posts/1/comments/1 and removed the references.

Thanks.
