### ISSUE TITLE
PHPCR\NodeType\ConstraintViolationException Property 'jcr:uuid' of node type 'mix:referenceable' is protected and cannot be modified

### ISSUE THREAD

**Issue by billsworld** [doctrine/phpcr-odm#697]
Trying to use:
```<field name="uuid" type="uuid" property="jcr:uuid"/>```

Thought I was in the clear on https://github.com/doctrine/phpcr-odm/pull/694 but I am getting this error now when I run my unit tests and fixtures.

I only got that after fixing this file https://github.com/phpcr/phpcr/blob/master/src/PHPCR/PropertyType.php to avoid another error
```Unknown type name (uuid) given.```

It seems the UUID field type still needs some work.

**Comment by dbu** [comment]
uuid is no phpcr field type, its an inherent property of nodes. the internal type of jcr:uuid is string. 
as discussed in #694 this should actually already work. there is also the AbstractMappingDriverTest::testUuidMapping that ensures that the xml mapping is loaded as expected.

oooh, sorry, i think i misdirected you. the mapping is not `<field ...` but `<uuid name="uuid" />` (which makes sense, its not a phpcr field type). this is documented here: http://doctrine-orm.readthedocs.org/projects/doctrine-phpcr-odm/en/latest/reference/association-mapping.html#referenceable-documents - i will fix the documentation at http://doctrine-orm.readthedocs.org/projects/doctrine-phpcr-odm/en/latest/reference/basic-mapping.html#doctrine-mapping-types as listing uuid there is misleading

**Comment by billsworld** [comment]
Got it. Kinda figured I was doing it wrong. Thanks.

**Comment by dbu** [comment]
sorry for the confusion i created. i hope it works now as expected. please close this issue if its working for you

**Comment by billsworld** [comment]
Works as expected. Converted over to Annotations b/c they seem to be more supported.

Thanks.
