### ISSUE TITLE
PHP syntax errors causing incompatibilities between doctrine/phpcr-bundle and doctrine/phpcr-odm

### ISSUE THREAD

**Issue by capelinventures** [doctrine/phpcr-odm#698]
Hi. I have a pretty huge app running PHP 5.5.30 with Symfony 2.5.12 and majorly stable dependencies tailored towards my framework version. When recently there was a need to add a CMS engine to the app, I decided to add the Symfony CMF as a sidekick (and of course PHPCR):

```
$ composer show |grep -i phpc|grep -v collection
doctrine/phpcr-bundle                        1.3.0              Symfony DoctrinePHPCRBundle
doctrine/phpcr-odm                           1.3.0              Object-Document-Mapper for PHPCR
jackalope/jackalope                          1.2.7              Jackalope PHPCR library
phpcr/phpcr                                  2.1.2              PHP Content Repository interfaces
phpcr/phpcr-utils                            1.2.9              PHP Content Repository implementation independant utilities
```

After configuring it accordingly to the Symfony tutorials found http://symfony.com/doc/1.0/cmf/cookbook/installing_configuring_doctrine_phpcr_odm.html it still renders a silly PHP syntax/usage error when trying to clear the cache:
```
$ /usr/bin/php -d memory_limit=-1 app/console cache:clear

Clearing the cache for the dev environment with debug true

  [Symfony\Component\Debug\Exception\ContextErrorException]
  Runtime Notice: Non-static method Doctrine\ODM\PHPCR\Tools\Helper\UniqueNodeTypeHelper::checkNodeTypeMappings() should not be called statically, assuming $this from incompatible context in .../vendor/doctrine/phpcr-bundle/CacheWarmer/UniqueNodeTypeCacheWarmer.php line 66
```

Looking at the UniqueNodeTypeHelper class and it's call within the CacheWarmer - indeed it's a normal class with public method that is tried to be called statically... :)

How do I fix this without messing with CacheWarmer code alone and then breaking my deps?

**Comment by capelinventures** [comment]
I also noticed that phpcr-bundle 1.3.1 (precisely commit d5e818e970ef5b0fc38700c40e92148312b8b020 ) fixes this issue YET it also drops compatibility with Symfony 2.5.* pretty much for no reason, even though the commit about dropping compatibility for 2.5 is newer (b0e80c61b6e489eec74c2d6bae7d156a8e6909ae)...

**Comment by capelinventures** [comment]
Not the prettiest approach, but...
```
    "require": {
        ...
        "doctrine/phpcr-bundle": "1.3.0",
        ...
    },
    "scripts": {
        ...
        "post-install-cmd": [
            "/bin/sh post-composer-install.sh",
            ...
        }
        ...
    }
```

```
$ cat post-composer-install.sh
#!/bin/sh
/usr/bin/patch -p0 < phpcr-bundle-1.3.0-fix.patch
```

```
$ cat phpcr-bundle-1.3.0-fix.patch
+++ vendor/doctrine/phpcr-bundle/CacheWarmer/UniqueNodeTypeCacheWarmer.php	2016-03-31 17:46:08.000000000 +0200
@@ -62,8 +62,10 @@
      */
     public function warmUp($cacheDir)
     {
+        $helper = new UniqueNodeTypeHelper();
+
         foreach ($this->registry->getManagers() as $documentManager) {
-            UniqueNodeTypeHelper::checkNodeTypeMappings($documentManager);
+            $helper->checkNodeTypeMappings($documentManager);
         }
     }
 }
```

What else could I do... :(

**Comment by dbu** [comment]
hi @capelinventures 

sorry for that one. we dropped symfony 2.5 support because we ran into  some compatibility issues with the versions of symfony that we declare a conflict with. as symfony 2.5 is no longer supported, we decided to not add hacks to work around the issue but only support symfony versions that do not have the problem. (before you ask, i don't remember what the exact problem was).

i think your options (short of upgrading symfony to a maintained version, which hopefully you eventually get to do for security reasons...) are to pin the phpcr bundle to that specific commit that fixes the bug without declaring the conflict, and check if that version works for you.  to pin, you would do ` "doctrine/phpcr-bundle": "d5e818e970ef5b0fc38700c40e92148312b8b020 as 1.3.0",`. or keep your hack until you can upgrade symfony.

ftr, this issue is about [the symfony bundle](https://github.com/doctrine/DoctrinePHPCRBundle), not the phpcr-odm library.

**Comment by capelinventures** [comment]
Hi @dbu, thanks a lot for your reply. I'm aware that 2.5.* is pretty much outdated, but currently in our company updating *entire stack* is a bit out of the question - that's why I sometimes have to run into those compatibility hacks and patches myself. Still again thanks for your reply. Hoping that leaving this ticket here in your Q&A base might help some1 in similar situation to mine. :)

**Comment by capelinventures** [comment]
@dbu: Also for your "ftr", the compatibility issue indeed *is* about Symfony Bundle, but I'd also say an actual programmatic syntax error within stable-marked version of phpcr-bundle (and thus my "hacky" solution to this) belongs here. ;)
