### ISSUE TITLE
2.0 branch behind dev-master

### ISSUE THREAD

**Issue by dantleech** [doctrine/phpcr-odm#719]
The 2.0 branch does not, for example, contain the `@ChildClasses` feature.

Why do we have a `2.0` branch? Should we not alias `dev-master` as `2.0-dev` ?

**Comment by dbu** [comment]
the branch is for https://github.com/doctrine/phpcr-odm/pull/711 and mainly deletes deprecated files.

i don't know why we did not merge that - probably because we did not really want to start 2.0 development? anyways, lets discuss in #711
