### ISSUE TITLE
PHP7-compatible branch ?

### ISSUE THREAD

**Issue by rivaros** [doctrine/phpcr-odm#720]
Will you make a PHP7-compatible branch with deprecated class-names, like String, Int, Float removed?

**Comment by dantleech** [comment]
Those annotations are already deprecated, you can use [@Field](http://docs.doctrine-project.org/projects/doctrine-phpcr-odm/en/latest/reference/annotations-mapping.html#field)

**Comment by rivaros** [comment]
know about it, but many commands like
`php app/console assetic:dump` are causing error, because of physical existence of these files

**Comment by rivaros** [comment]
```
> PHP Stack trace:
> PHP   1. {main}() /project/app/console:0
> PHP   2. require()  /project/app/console:17
> PHP   3. Doctrine\Common\Annotations\AnnotationRegistry::registerFile()  /project/app/autoload.php:12
> PHP   4. require_once()  /project/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php:64
```

**Comment by rivaros** [comment]
This line contains:
`AnnotationRegistry::registerFile(__DIR__.'/../vendor/doctrine/phpcr-odm/lib/Doctrine/ODM/PHPCR/Mapping/Annotations/DoctrineAnnotations.php');`

I remember it was in documentation. Maybe not necessary any more?

**Comment by dbu** [comment]
correct, the AnnotationRegistry is not needed anymore. the annotation classes can be autoloaded like normal classes. see for example https://github.com/symfony-cmf/cmf-sandbox/blob/master/bin/console
