### ISSUE TITLE
Making query over multivalue assoc field

### ISSUE THREAD

**Issue by milosnovi** [doctrine/phpcr-odm#725]
Hi there,

Is it possible to make query with QueryBuilder which will mach multivalue assoc field by exact combination of index and value  

something like this
$qb->andWhere()->like()->field("a.testFieldAssoc1")->literal("key1=>value1")->end();

where documents with type 'a' has property 'testFieldAssoc1': ["key1" => "value1", "key2"=>"value2"...]

thx,
Milos

**Comment by dbu** [comment]
unfortunately no. JCR/PHPCR does not have the concept of associative arrays/hashmaps, it only knows plain arrays of values. for phpcr-odm, we split the map into two arrays, one for keys and one for values. if you know the keys in advance, you can model them as explicit properties and they will become easy to query. or you can map the PHPCR Node onto the document and use the NodeInterface methods to set and read additional properties with dynamic names and do a PHPCR (as opposed to PHPCR-ODM) query on those.
