### ISSUE TITLE
Uuid generation on document change to 'referenceable'

### ISSUE THREAD

**Issue by syeo66** [doctrine/phpcr-odm#729]
I had some objects which did not need to be referenceable in earlier releases. Some recent changes required to change that and make it referenceable. However I don't see a way to add the Uuid field to the existing documents.

I tried something like this:

```php
        $queryBuilder = $documentManager->getRepository(Item::class)
                ->createQueryBuilder('a');
        $queryBuilder->where()->not()->fieldisset('a.uuid');
        $items = $queryBuilder
                ->getQuery()
                ->execute();
        foreach ($items as $item) {
            $item->setUpdatedAt(new \DateTime());
            $documentManager->persist($item);
        }
        $documentManager->flush();
```

But the objects still don't have a Uuid. Setting the uuid directly did not work either - which was to be expected (since it is only allowed on object creation).

Now I feel like I'm stuck. How can I migrate all the existing objects?

**Comment by dbu** [comment]
i assume you added the jcr:referenceable in the document annotations?
actually not sure if we update mixins on changes.

can you try on phpcr level? if you get the node at the path and call
$node->addMixin?

**Comment by syeo66** [comment]
Thank you. It seems like this lead me down the correct path. 
```php
        foreach ($answers as $answer) {
            $answersCount++;
            $node = $answer->getNode();
            if (!$answer->getNode()->hasProperty('jcr:uuid')) {
                $node->addMixin('mix:referenceable');
                $node->setProperty('jcr:uuid', $node->getIdentifier());
            }
            $documentManager->persist($answer);
            $documentManager->flush();
        }
```

Seems to do the trick.

**Comment by syeo66** [comment]
Just for the record (and answer your question):

> i assume you added the jcr:referenceable in the document annotations?

Yes, I did.

**Comment by dbu** [comment]
cool! i am surprised that you have the line `$node->setProperty('jcr:uuid', $node->getIdentifier());`. just addMixin should be enough to let phpcr autogenerate the uuid i think.

i guess phpcr-odm could use some love in this regard, to detect such changes or provide some sort of migration command... a first step would be a cookbook entry. i created https://github.com/doctrine/phpcr-odm-documentation/issues/83 to track that. if you would have time to write a short entry for that, it would be much appreciated of course ;-)

**Comment by syeo66** [comment]
To be honest I did not check setting the uuid is actually needed. I'll try that if I find some time (and will also see if I can add something to the cookbook). However right now I'm knee-deep in my current project.
Anyway, thanks for your help.

**Comment by dbu** [comment]
sure, glad i could help. if you find the time, great, otherwise somebody
else might at some point...
