### ISSUE TITLE
Extending Document objects

### ISSUE THREAD

**Issue by petforsberg** [doctrine/phpcr-odm#732]
In the [documentation](https://symfony.com/doc/current/cmf/tutorial/getting-started.html) there is:

> You may not, however, extend one class from the other, as this will cause unintended behavior in the admin integration later on.

Any chances for allowing to extend one class from another in PHPCR ODM Documents (instead of being forced to using traits)? It'd be a nice feature-fix, since otherwise it makes hard to use many other 3rd party components, which expect their provided model to be extended.

**Comment by dbu** [comment]
uh, that is not well formulated. extending documents actually works. the only caveeat is that if you use sonata admin *and* you have an admin for a class and another class that extends that first class, you will see all items of the extending class in the admin of the base class as well, which likely is not what you wanted. having a common abstract base class is no problem. 

having two concrete classes that are both documents can be a mess in sonata admin, but that is the only restriction there is.

**Comment by dbu** [comment]
the whole comment was only relevant for php 5.3 (as later there are traits). the introduction should not explain edge case interactions with sonata, deleting the confusing note: https://github.com/symfony-cmf/symfony-cmf-docs/pull/791
