### ISSUE TITLE
method name confusion UOW::getDocumentIdentifier() vs. UOW::getDocumentId()

### ISSUE THREAD

**Issue by aemaething** [doctrine/phpcr-odm#742]
Hi guys,

maybe I miss a thing, but:

At doctrine/mongodb-odm the method to get the document identifier is called "getDocumentIdentifier", see https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/UnitOfWork.php#L2777

At doctrine/doctrine2 the method is called getEntityIdentifier(), see: 
https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/UnitOfWork.php#L2905

At doctrine/phpcr-odm the analogue method is called getDocumentId(), see:
https://github.com/doctrine/phpcr-odm/blob/master/lib/Doctrine/ODM/PHPCR/UnitOfWork.php#L3124

The method ReferenceRepository::getIdentifier() of doctrine/data-fixtures tries do deal with the ORM/ODM method name, as you can see around:
https://github.com/doctrine/data-fixtures/blob/master/lib/Doctrine/Common/DataFixtures/ReferenceRepository.php#L91

In case of ODM always "$uow->getDocumentIdentifier()" is called, though the method is named getDocumentId() at PHPCR's UOW.

So, what's the best fix here? Rename the method or extend the method ReferenceRepository::getIdentifier() to handle the PHPCR case?

Best,
Achim

**Comment by dbu** [comment]
thanks for the analysis! the uow is not standardized by interfaces. i think the correct way is to change the data-fixtures to check the type of repository and call the correct method, like its done in another method: https://github.com/doctrine/data-fixtures/blob/1b6c7dd1dc9d2ecbb7c0daa15d86a437c062e347/lib/Doctrine/Common/DataFixtures/ReferenceRepository.php#L251-L254

the commend that this is "ODM" in that case is probably from the time when fixtures only supported orm and mongo... can you do a pull request on the data fixtures for this? the class already imports the phpcr manager as PhpcrDocumentManager.

**Comment by aemaething** [comment]
No problem. I'll do it on weekend.

Best,
Achim

**Comment by dbu** [comment]
cool. awesome bug report by the way! digging up the problem this precisely makes it really easy for me as maintainer to see the problem. thanks!

**Comment by dbu** [comment]
fixed in https://github.com/doctrine/data-fixtures/pull/255
