### ISSUE TITLE
PHP 7 compability issue

### ISSUE THREAD

**Issue by fabriciojs** [doctrine/phpcr-odm#746]
I am trying to a upgrade a *Symfony 2.8.22* / *CMF 1.3.0* system from PHP 5.6 to PHP 7.1 but I am unable to do so because of this package at version tag `1.4.2`.

What happens: even though the `composer.json` allows for PHP 7, the package still has the annotation classes `String`, `Int` and `Float` that became reserved words - and automatic cache tries to load them, throwing errors and making the application inoperable.

I see even though it's deprecated [DoctrineAnnotations.php](https://github.com/doctrine/phpcr-odm/blob/1.4.2/lib/Doctrine/ODM/PHPCR/Mapping/Annotations/DoctrineAnnotations.php) is one of the places trying to load them by default. How can I avoid that method?

Anyone faced this? Is there a way I can avoid loading those annotations? I see that even at version 2.0 we still have the classes there, so maybe I am missing something obvious about how to make it work with  PHP 7.

Thanks in advance!

**Comment by dbu** [comment]
we build this successfully on travis with php 7 so it seems possible: https://github.com/doctrine/phpcr-odm/blob/master/.travis.yml

could it be that you include the DoctrineAnnotations.php in autoload.php or anywhere? afaik at the beginning this was a required step in the setup. annotations can now be autoloaded normally so no need for such a thing anymore. or do you have some extra class cache layer that pre-caches all classes in your project? afaik that would not be standard behaviour of php.

for version 2 we should probably remove the file - but i don't expect that 2.0 is released very soon.

**Comment by fabriciojs** [comment]
@dbu Thanks for your answer!

Well we don't explicitly load DoctrineAnnotations.php, but as far as I can tell right now, it's the DistributionBundle ScriptHandler::buildBootstrap method which is trying to load it (and also it is the one trying to pre-cache all of the annotations by this mean).

I am assuming the issue lies either on the DistributionBundle version I am using or its settings - so I guess we can close this in terms of an actual issue from `phpcr-odm`, although would be good to have here a record of the solution - maybe adding a check in `DoctrineAnnotations.php` for PHP version and giving a better error message would be good for someone else who faces this. I can provide a PR on that direction if you see fit, please let me know.

I will be updating this with my progress. (feel free to close it though)

**Comment by dbu** [comment]
could you grep through your project codebase (including vendors) if there
is an explicit mention of the file anywhere? and maybe check if orm has a
similar file and if you find mentions in some exclude list? once we have
some solution, a php version check and helpful error in the file is a great
idea!

Am 23.06.2017 7:03 nachm. schrieb "Fabrício José Souza" <
notifications@github.com>:

**Comment by dbu** [comment]
we tagged 1.4.3 which should work with PHP 7.1 and 7.2
