### ISSUE TITLE
Array Equality Checking for reordering in UnitOfWork

### ISSUE THREAD

**Issue by UFTimmy** [doctrine/phpcr-odm#787]
Howdy,

This section of the computeChangeSet method checks to see if the children were reordered:
https://github.com/doctrine/phpcr-odm/blob/master/lib/Doctrine/ODM/PHPCR/UnitOfWork.php#L1419

It does that by checking $originalNames vs $childNames. However, the two arrays are built using slightly different methods, which can result in this method thinking children were re-ordered when they were not.

I have a document that has these as children:

`Array
(
    [0] => Title
    [1] => PageSettings
    [2] => CascadeSettings
    [3] => Blocks
    [4] => 2008
    [5] => 2009
    [6] => 2010
    [7] => 2011
    [8] => 2012
    [9] => 2013
    [10] => 2014
    [11] => 2015
    [12] => 2016
    [13] => 2017
    [14] => 2018
)`

Basically, it has a few properties that are there for all of my documents, the ones that are strings. Then it also has true children pages, that are based on the name of the page. In this case, those pages are named after years. This is the issue, in $childNames, those year pages are strings, but in $originalNodeNames, they are integers.

So the equality check for the two arrays will always be false.

It looks like the originalNames are being built here:
https://github.com/doctrine/phpcr-odm/blob/master/lib/Doctrine/ODM/PHPCR/ChildrenCollection.php#L229

Since they are being built from array_keys, and they are numeric, they are coming over as type int. Whereas the childNames is coming from the actual node name, so it stays a string.

I'd be happy to fix this, if you can help guide me towards the right way.

Off the top of my head, I can see two solutions:

1. Change the ChildrenCollection to always keep the originalNodeNames as type string. This seems easy enough, but I don't know enough to know what side effects it may have.
2. Add a second check to computeChangeSet, after calcuating $reordering. In this case, $reordering is empty, because nothing has really moved. So I could add an if statement that only marked the document as changed if reordering has a value.

FWIW, this is causing a breakage when it comes to the CMF's AutoRouting. I am moving a folder, and relying on LeaveRedirect to move routes for me. In theory, only the document I am moving should 
be flagged as changed, and then its routes get moved.

However, some child documents are also being flagged as changed due to this bug, and then their routes are generated. However, the intermediate nodes are generated as Generic, and not AutoRoutes, and a Node is protected error is generated later when trying to change them to AutoRoutes and assign them a uuid.

I appreciate your help and time spent reading over this (lengthy) issue.

**Comment by dbu** [comment]
thanks a lot for this detailed report! yeah, good old UnitOfWork :thinking: 

do i understand correctly that the problem is `"2015"` vs `2015`? indeed: https://3v4l.org/TIeQW - just great, thanks PHP :-(

as those keys are always phpcr node names, we know they are strings. imho we should change the comparison to `!=` instead of `!==` https://3v4l.org/oLHhb . casting all array elements to string before comparing could be relatively expensive, as it would be done a lot on large document trees.

if you want to work on this, is suggest to first try to build a minimal test case that shows the problem, and then change the comparison to non-strict.

**Comment by UFTimmy** [comment]
You are correct that the fundamental difference is the 2015 vs “2015”. 

But == won’t work as it does not check the order of the keys, just the presence of them. 
https://3v4l.org/iZc7p

What about just checking that the $reorder variable is set to a non empty array after calculating the reorder, and if not don’t schedule the document for update?

**Comment by UFTimmy** [comment]
Thanks for the suggestion, I think changing it to `!=` will work just fine. I forked and made the change, and have been using it in my application just fine, and it fixes the issue while still successfully detecting reorders.

But I don't have much experience with UnitTests. I got the UnitOfWork tests to run, but I am not sure how to write a test to cover this.

I would think I would want to:

- make a parent node, with multiple child nodes with integer names.
- persist and commit the node
- then do nothing, call computeChangeSets, and make sure the uow's scheduledUpdates is an empty array.

I think with the current code, that test would fail, but once the strictness was removed it would pass.

I could see an additional test where the same thing happened, but the children are reordered and the test passes if there is a scheduled update.

Any assistance you could provide would be appreciated.

**Comment by dbu** [comment]
i guess its technically not a unit test but more of a functional test, because it uses the database and all ;-)

your approach sounds correct to me. the test to add to is called ReorderTest. actually, it should be enough to change one of the named children to a number-name on this line: https://github.com/doctrine/phpcr-odm/blob/50a82a8646c8e1a4d0b2380e83a7faf095ff2502/tests/Doctrine/Tests/ODM/PHPCR/Functional/ReorderTest.php#L100

**Comment by dbu** [comment]
(edited the previous comment to explain it better)

**Comment by UFTimmy** [comment]
Howdy,

My project finally cleared, and I had time to implement the unit test. You can see it here:
https://github.com/UFTimmy/phpcr-odm/commit/2c908a3b3a31b7363299f8dd11d6057fc6f89da4#diff-0fdc105115539a4aae060e42657b1cf2

The test fails with the strict equality checking, but passes once its changed to loose.

Everything look ok, would a pull request with the test and the fix to non strict equality checking be ok?

Thank you!
